version: '3'
services:
 postgres:
   container_name: database
   build: ./database
   restart: on-failure
   environment:
     - POSTGRES_DB=${POSTGRES_DB}
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
   expose:
     - "5432"
   networks:
     - experian
 backend:
   container_name: backend
   build: ./backend
   restart: on-failure
   depends_on:
     - postgres
   ports:
     - "8080:8080"
   networks:
     - experian

networks:
    experian:
        driver: bridge