version: '3'
services:
 postgres:
   container_name: database
   build: ./database
   restart: on-failure
   environment:
     - POSTGRES_DB=${POSTGRES_DB}
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
   ports:
     - "5432:5432"
 backend:
   container_name: backend
   build: ./backend
   restart: on-failure
   depends_on:
     - postgres
   ports:
     - "8080:8080"
 frontend:
   container_name: frontend
   build: ./frontend
   depends_on:
     - backend
   ports:
     - "3000:3000"